### ISSUE TITLE
Child Theme

### ISSUE THREAD

**Issue by jeanmatthieud** [swashata/wp-webpack-script#1167]
Hi ! 
I'm quite interested by your project; having a better tool to develop and build WP theme and plugin is mandatory for me!

I'm trying to upgrade one of my existing theme.
This theme is a child theme of `hello-elementor`.

After initializing the theme following the documentation, I launched `npm run start`, and got the following error:
```
Fatal error: Uncaught LogicException: Manifest [...]/wp-content/themes/hello-elementor/dist/app/manifest.json does not exist. in [...]\wp-content\themes\suv-wp-theme\vendor\wpackio\enqueue\inc\Enqueue.php:394 
Stack trace: 
#0 [...]\wp-content\themes\suv-wp-theme\vendor\wpackio\enqueue\inc\Enqueue.php(292): WPackio\Enqueue->getManifest('app') 
#1 [...]\wp-content\themes\suv-wp-theme\vendor\wpackio\enqueue\inc\Enqueue.php(170): WPackio\Enqueue->getAssets('app', 'main', Array) 
#2 [...]\wp-content\themes\suv-wp-theme\vendor\wpackio\enqueue\inc\Enqueue.php(228): WPackio\Enqueue->register('app', 'main', Array) 
#3 [...]\wp-content\themes\suv-wp-theme\functions.php(8): WPackio\Enqueue->enqueue('app', 'main', Array) 
#4 [...]\wp-settings.php(514): include('F:\\dev\\se-unsa-...') 
#5 [...]\wp in [...]\wp-content\themes\suv-wp-theme\vendor\wpackio\enqueue\inc\Enqueue.php on line 394
```

Does wpack works with child themes ?

**Comment by jeanmatthieud** [comment]
Sorry, I didn't check the constructor of Enqueue. I will try again.
