### ISSUE TITLE
Child-Theme Configuration

### ISSUE THREAD

**Issue by paulHasselkuss** [swashata/wp-webpack-script#956]
I want to use wpack within a child-theme. I followed the guides closely, but the site throws an error
 and complains about a missing manifest file within the parent-theme (!):

```
Fatal error: Uncaught LogicException: Manifest /srv/www/ais-dev/public_html/wp-content/themes/parent/dist/app/manifest.json does not exist. in /srv/www/ais-dev/public_html/wp-content/themes/child/vendor/wpackio/enqueue/inc/Enqueue.php:394 Stack trace: #0 /srv/www/ais-dev/public_html/wp-content/themes/child/vendor/wpackio/enqueue/inc/Enqueue.php(292): WPackio\Enqueue->getManifest() #1 /srv/www/ais-dev/public_html/wp-content/themes/child/functions.php(8): WPackio\Enqueue->getAssets() #2 /srv/www/ais-dev/public_html/wp-settings.php(497): include('/srv/www/ais-de...') #3 /srv/www/ais-dev/public_html/wp-config.php(80): require_once('/srv/www/ais-de...') #4 /srv/www/ais-dev/public_html/wp-load.php(37): require_once('/srv/www/ais-de...') #5 /srv/www/ais-dev/public_html/wp-blog-header.php(13): require_once('/srv/www/ais-de...') #6 /srv/www/ais-dev/public_html/index.php(17): require('/srv/www/ais-de...') #7 {main} thrown in /srv/www/ais-dev/public_html/wp-content/themes/child/vendor/wpackio/enqueue/inc/Enqueue.php on line 394
```

My `functions.php` looks as follows:

```PHP
<?php 
// Require the composer autoload for getting conflict-free access to enqueue
require_once __DIR__ . '/vendor/autoload.php';

// Instantiate
$enqueue = new \WPackio\Enqueue( 'child', 'dist', '1.0.0', 'theme', false);
$assets = $enqueue->getAssets( 'app', 'main', [
	'js' => true,
	'css' => true,
	'js_dep' => [],
	'css_dep' => [],
	'in_footer' => true,
	'media' => 'all',
] );

add_action( 'wp_enqueue_scripts', 'child_style' );
function child_style() {
	foreach ( $csses as $css ) {
		if ( $config['css'] ) {
			wp_enqueue_style( $css['handle'], $css['url'], $config['css_dep'], '1.0.0', 'all' );
		}
	}
}
```
Am I doing something wrong?

**Comment by BiswasSuman** [comment]
Maybe your file will be like 
```php
<?php

use WPackio\Enqueue;

require_once __DIR__ . '/vendor/autoload.php'; 

class MyPluginInit {

	public $enqueue;

	public function __construct() {
    $this->enqueue = new Enqueue( 'expWpackIo', 'dist', '1.0.0', 'theme', __FILE__ );
    
		add_action( 'wp_enqueue_scripts', [ $this, 'theme_enqueue' ] );
	}

	public function theme_enqueue() {
		$this->enqueue->enqueue( 'app', 'mobile', [ ] );
	}
}

new MyPluginInit();
```

**Comment by BiswasSuman** [comment]
You have to pass the `themeType` as sixth parameter in `Enqueue`
`themeType`   If this is a theme, then you can declare if it is a `child` or `regular` theme.
```php
$enqueue = new \WPackio\Enqueue( 'child', 'dist', '1.0.0', 'theme', false, 'child' );
```

**Comment by paulHasselkuss** [comment]
Thanks, after adding `child` it works as expected. For future reference, the working code can be found below (note that, however, parent's styles are not yet unhooked and may overwrite the child's styles):

```PHP
<?php 

require_once __DIR__ . '/vendor/autoload.php';

// Do stuff through this plugin
class MyPluginInit {
	/**
	 * @var \WPackio\Enqueue
	 */
	public $enqueue;

	public function __construct() {
		// It is important that we init the Enqueue class right at the plugin/theme load time
		$this->enqueue = new \WPackio\Enqueue(
			// Name of the project, same as `appName` in wpackio.project.js
			'child',
			// Output directory, same as `outputPath` in wpackio.project.js
			'dist',
			// Version of your plugin
			'1.0.0',
			// Type of your project, same as `type` in wpackio.project.js
			'theme',
			// Plugin location, pass false in case of theme.
			false,
			// Type of the theme, 'regular' or 'child'
			'child'
		);
		// Enqueue a few of our entry points
		add_action( 'wp_enqueue_scripts', [ $this, 'plugin_enqueue' ] );
	}

	public function plugin_enqueue() {
		// Enqueue files[0] (name = app) - entryPoint main
		$this->enqueue->enqueue( 'app', 'main', [] );
	}
}


// Init
new MyPluginInit();
```

I think child-theme support is not yet covered by the docs. Is it possible to add the corresponding documentation?

**Comment by ruelluna** [comment]
Waiting for merge: https://github.com/swashata/wp-webpack-script/pull/971

**Comment by swashata** [comment]
There's a failing test that I need to fix from my end. But currently my Mac is submitted for repair and can't work on Windows. As soon as I get my Mac back, I will fix the failing test and merge.

**Comment by swashata** [comment]
It has been merged and released.
